version: '3.8'

services:
  postgres_db:
    container_name: postgres_db 
    image: postgres:17-alpine 

    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: hometrack_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: hometrack_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hometrack-network
    restart: unless-stopped

  hometrack-api:
    build:
      context: .
      dockerfile: HomeTrack.Api/Dockerfile  # Đường dẫn đến Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres_db
    volumes:
      - hometrack_uploads:/app/wwwroot/uploads
    networks:
      - hometrack-network


volumes:
  postgres_data:
  hometrack_uploads:
    driver: local

networks:
  hometrack-network:
    driver: bridge
