# ----------- BUILD STAGE ------------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env

WORKDIR /src

# Sao chép file .csproj để tận dụng cache
COPY HomeTrack.Api.csproj ./HomeTrack.Api/

WORKDIR /src/HomeTrack.Api

# Khôi phục package
RUN dotnet restore

# Sao chép toàn bộ source code
COPY . ./

# Publish ra thư mục riêng
RUN dotnet publish "HomeTrack.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

# ----------- RUNTIME STAGE ------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime-env

WORKDIR /app

# Copy kết quả publish từ build stage
COPY --from=build-env /app/publish ./

# Mở port 8001
EXPOSE 8001

# Cấu hình để ứng dụng lắng nghe mọi địa chỉ
ENV ASPNETCORE_URLS=http://+:8001
# ENV ASPNETCORE_ENVIRONMENT=Production

# Lệnh chạy ứng dụng
ENTRYPOINT ["dotnet", "HomeTrack.Api.dll"]
